name = "digitek-lab"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CONTACT_TO = "ameer.itoa@gmail.com"
CONTACT_FROM = "noreply@digiteklab.com"

# This natively binds Cloudflare's Email Routing to your function
[[send_email]]
name = "EMAIL"
destination_address = "ameer.itoa@gmail.com"